export const typesEnums = {
  FETCH_CRYPTO: "FETCH_CRYPTO",
  LOAD_CRYPTO: "LOAD_CRYPTO",
  NEXT_PAGE: "NEXT_PAGE",
  PREV_PAGE: "PREV_PAGE",
  GET_CRYPTO_SOCIAL_STATUS: "GET_CRYPTO_SOCIAL_STATUS",
  GET_CRYPTO_TOP_MARKETS: "GET_CRYPTO_TOP_MARKETS",
  GET_CRYPTO_DETAILS: "GET_CRYPTO_DETAILS",
};
